import { useEffect, useState } from "react";
import { History, Loader2 } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { supabase } from "@/integrations/supabase/client";
import { format, parseISO } from "date-fns";
const db = supabase as any;
export function ScheduleHistoryDialog({ scheduleId, open, onOpenChange }: { scheduleId: string | null; open: boolean; onOpenChange: (open: boolean) => void }) {
  const [items, setItems] = useState<any[]>([]), [loading, setLoading] = useState(false);
  useEffect(() => { if (!open || !scheduleId) return; let active=true; setLoading(true); (async()=>{ const {data,error}=await db.from("work_schedule_history").select("id,action,changed_by,changed_at,old_data,new_data").eq("schedule_id",scheduleId).order("changed_at",{ascending:false}); if(active){if(!error)setItems(data||[]);setLoading(false);} })(); return()=>{active=false;}; },[open,scheduleId]);
  const labels:Record<string,string>={created:"Criada",updated:"Alterada",confirmed:"Confirmada",deleted:"Excluída"};
  const describe=(item:any)=>{const o=item.old_data||{},n=item.new_data||{};if(item.action==="created")return"Escala criada";if(item.action==="deleted")return"Escala excluída";if(item.action==="confirmed")return"Funcionário confirmado";const c:string[]=[];if(o.employee_id!==n.employee_id)c.push("funcionário");if(o.date!==n.date)c.push("data");if(String(o.start_time||"").slice(0,5)!==String(n.start_time||"").slice(0,5)||String(o.end_time||"").slice(0,5)!==String(n.end_time||"").slice(0,5))c.push("horário");if(Number(o.daily_rate||0)!==Number(n.daily_rate||0))c.push("valor");if(o.environment_id!==n.environment_id)c.push("ambiente");return c.length?"Alteração: "+c.join(", "):"Escala atualizada";};
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="w-[calc(100%-1rem)] max-w-lg rounded-xl"><DialogHeader><DialogTitle className="flex items-center gap-2"><History className="h-5 w-5"/>Histórico da escala</DialogTitle></DialogHeader><div className="max-h-[65dvh] overflow-y-auto space-y-3">{loading?<div className="py-8 flex justify-center"><Loader2 className="h-6 w-6 animate-spin text-primary"/></div>:items.length?items.map(i=><div key={i.id} className="rounded-lg border p-3"><div className="flex items-center gap-2"><Badge variant="secondary">{labels[i.action]||i.action}</Badge><span className="text-xs text-muted-foreground">{format(parseISO(i.changed_at),"dd/MM/yyyy HH:mm")}</span></div><p className="mt-2 text-sm font-medium">{describe(i)}</p><p className="mt-1 text-xs text-muted-foreground">Usuário: {i.changed_by?String(i.changed_by).slice(0,8):"sistema"}</p></div>):<p className="py-8 text-center text-sm text-muted-foreground">Nenhum histórico encontrado.</p>}</div></DialogContent></Dialog>;
}
